# Generated by Django 2.2.3 on 2022-07-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=30)),
                ('serie', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
                ('cantidad', models.CharField(max_length=3)),
                ('tipo', models.CharField(max_length=10)),
                ('categoria', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Dispositivos',
            },
        ),
    ]
