# Generated by Django 2.2.3 on 2022-08-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoinventario', '0003_auto_20220730_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('departamento', models.CharField(max_length=50)),
                ('hotel', models.CharField(max_length=50)),
                ('upated', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='assets',
            name='fecha_compra',
            field=models.DateField(max_length=10, null=True),
        ),
    ]
