# Generated by Django 2.2.3 on 2022-08-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoinventario', '0004_auto_20220803_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='fecha_compra',
            field=models.DateField(),
        ),
    ]
