# Generated by Django 2.2.3 on 2022-08-04 17:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoinventario', '0005_auto_20220804_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='fecha_compra',
        ),
        migrations.AddField(
            model_name='assets',
            name='año_compra',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
