# Generated by Django 2.2.3 on 2022-08-05 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoinventario', '0007_auto_20220804_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='id_series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectoinventario.Assets'),
        ),
    ]
