# Generated by Django 2.2.3 on 2022-08-05 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoinventario', '0008_clientes_id_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='id_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectoinventario.Assets'),
        ),
    ]
