# Generated by Django 2.2.3 on 2022-08-05 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoinventario', '0009_auto_20220805_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='id_series',
            new_name='asset',
        ),
    ]
