# Generated by Django 2.2.3 on 2022-08-05 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoinventario', '0010_auto_20220805_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assets',
            old_name='id_asset',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='id_clientes',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectoinventario.Assets', to_field='id_asset'),
        ),
    ]
