# Generated by Django 2.2.3 on 2022-08-05 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoinventario', '0011_auto_20220805_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectoinventario.Assets'),
        ),
    ]
